import type { LucideIcon, LucideProps } from 'lucide-react'
import {
  AlignLeft,
  ArrowLeftRight,
  BarChart3,
  Bell,
  Bold,
  BookOpen,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDot,
  Clock3,
  Code2,
  Download,
  Eye,
  EyeOff,
  FilePenLine,
  FileText,
  Folder,
  FolderInput,
  FolderOpen,
  FolderPlus,
  GripVertical,
  Highlighter,
  Image,
  Info,
  Italic,
  LayoutGrid,
  Lightbulb,
  Link2,
  Link2Off,
  List,
  ListOrdered,
  Loader2,
  Minus,
  Monitor,
  MoreHorizontal,
  MoreVertical,
  PanelLeftOpen,
  Pen,
  Pencil,
  Pipette,
  Play,
  Plus,
  Puzzle,
  Quote,
  Redo2,
  RotateCcw,
  Scan,
  Search,
  Settings,
  Share2,
  Sigma,
  SlidersHorizontal,
  Sparkles,
  Strikethrough,
  Table2,
  TerminalSquare,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TriangleAlert,
  Underline,
  Undo2,
  User,
  Users,
  Video,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

export interface IconDefinition {
  Component: LucideIcon
  defaultStrokeWidth?: number
}

const catalog = {
  check: { Component: Check, defaultStrokeWidth: 3 },
  close: { Component: X },
  error: { Component: CircleAlert },
  info: { Component: Info },
  success: { Component: CircleCheck },
  warning: { Component: TriangleAlert },
  eye: { Component: Eye },
  eyeOff: { Component: EyeOff },
  chevronRight: { Component: ChevronRight },
  trash2: { Component: Trash2 },
  alignLeft: { Component: AlignLeft },
  arrowLeftRight: { Component: ArrowLeftRight },
  barChart3: { Component: BarChart3 },
  bell: { Component: Bell },
  bold: { Component: Bold },
  bookOpen: { Component: BookOpen },
  chevronDown: { Component: ChevronDown },
  chevronLeft: { Component: ChevronLeft },
  circleDashed: { Component: CircleDashed },
  circleDot: { Component: CircleDot },
  clock3: { Component: Clock3 },
  code2: { Component: Code2 },
  download: { Component: Download },
  filePenLine: { Component: FilePenLine },
  fileText: { Component: FileText },
  folder: { Component: Folder },
  folderInput: { Component: FolderInput },
  folderOpen: { Component: FolderOpen },
  folderPlus: { Component: FolderPlus },
  gripVertical: { Component: GripVertical },
  highlighter: { Component: Highlighter },
  image: { Component: Image },
  italic: { Component: Italic },
  layoutGrid: { Component: LayoutGrid },
  lightbulb: { Component: Lightbulb },
  link2: { Component: Link2 },
  link2Off: { Component: Link2Off },
  list: { Component: List },
  listOrdered: { Component: ListOrdered },
  loader2: { Component: Loader2 },
  minus: { Component: Minus },
  monitor: { Component: Monitor },
  moreHorizontal: { Component: MoreHorizontal },
  moreVertical: { Component: MoreVertical },
  panelLeftOpen: { Component: PanelLeftOpen },
  pen: { Component: Pen },
  pencil: { Component: Pencil },
  pipette: { Component: Pipette },
  play: { Component: Play },
  plus: { Component: Plus },
  puzzle: { Component: Puzzle },
  quote: { Component: Quote },
  redo2: { Component: Redo2 },
  rotateCcw: { Component: RotateCcw },
  scan: { Component: Scan },
  search: { Component: Search },
  settings: { Component: Settings },
  share2: { Component: Share2 },
  sigma: { Component: Sigma },
  slidersHorizontal: { Component: SlidersHorizontal },
  sparkles: { Component: Sparkles },
  strikethrough: { Component: Strikethrough },
  table2: { Component: Table2 },
  terminalSquare: { Component: TerminalSquare },
  thumbsDown: { Component: ThumbsDown },
  thumbsUp: { Component: ThumbsUp },
  triangleAlert: { Component: TriangleAlert },
  underline: { Component: Underline },
  undo2: { Component: Undo2 },
  user: { Component: User },
  users: { Component: Users },
  video: { Component: Video },
  zoomIn: { Component: ZoomIn },
  zoomOut: { Component: ZoomOut },
} as const

export type IconName = keyof typeof catalog

export const iconRegistry: Record<IconName, IconDefinition> = catalog

export const CheckIcon = (props: LucideProps) => <Check {...props} strokeWidth={3} />
export const CloseIcon = iconRegistry.close.Component
export const ErrorIcon = iconRegistry.error.Component
export const EyeIcon = iconRegistry.eye.Component
export const EyeOffIcon = iconRegistry.eyeOff.Component
export const InfoIcon = iconRegistry.info.Component
export const SuccessIcon = iconRegistry.success.Component
export const WarningIcon = iconRegistry.warning.Component
export const ChevronRightIcon = iconRegistry.chevronRight.Component
export const TrashIcon = iconRegistry.trash2.Component
